# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/RTV Pie',
                'doc_host': 'https://Analytics-Raising.github.io',
                'git_url': 'https://github.com/Analytics-Raising/RTV Pie',
                'lib_path': 'rtvpy'},
  'syms': { 'rtvpy.manipulate': {'rtvpy.manipulate.setRowAsHeader': ('manipulate.html#setrowasheader', 'rtvpy/manipulate.py')},
            'rtvpy.variable_decodings': { 'rtvpy.variable_decodings.getMeanings': ( 'variabale_decodings.html#getmeanings',
                                                                                    'rtvpy/variable_decodings.py'),
                                          'rtvpy.variable_decodings.pickAndAddColumns': ( 'variabale_decodings.html#pickandaddcolumns',
                                                                                          'rtvpy/variable_decodings.py')},
            'rtvpy.wandb_manager': { 'rtvpy.wandb_manager.loadWandbArtifact': ( '1_downloading_from_wandb.html#loadwandbartifact',
                                                                                'rtvpy/wandb_manager.py'),
                                     'rtvpy.wandb_manager.pushDatasetToWandb': ( '1_downloading_from_wandb.html#pushdatasettowandb',
                                                                                 'rtvpy/wandb_manager.py')}}}
